### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by zt-wang19** [Text2TCS/Term-Extraction-With-Language-Models#1]
I run the `Term_Extraction_Token_Classifier.ipynb` and got the error above when it comes to `trainer.train()`.
I didn't change any code,and installed the packages of the correct version.
So how did the error occur? Maybe it's inside the data processing procedure

**Comment by lwachowiak** [comment]
Hi, 
thanks for pointing that out! There was a bug in the preprocessing pipeline. I made an updated version of script available.  I also ran it with the package versions  currently installed on Google Colab and that also works. 
Also, be careful that your ACTER data has the same folder structure as the one used in the code.
